# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-18 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(blank=True, max_length=300, null=True)),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('hotel_name', models.CharField(max_length=300)),
                ('room_type', models.IntegerField(choices=[(1, b'Standard Room'), (2, b'King Room'), (3, b'Deluxe Room')])),
                ('_status', models.IntegerField(blank=True, choices=[(1, b'future reservation'), (2, b'guest is in-house'), (3, b'guest checked out')], help_text='service field for state property', null=True)),
                ('_state_modified', models.DateTimeField(blank=True, help_text='just in order to track when the last time of state change', null=True)),
            ],
        ),
    ]
